# ============================================================================
# docker-compose.env.yaml — окружение для BMFT бота (БЕЗ самого бота)
# ============================================================================
# Использование:
#   docker-compose -f docker-compose.env.yaml up -d    # Запуск окружения
#   docker-compose -f docker-compose.env.yaml down     # Остановка
#   docker-compose -f docker-compose.env.yaml down -v  # Остановка + очистка volumes
# ============================================================================
# Что включено:
# - PostgreSQL 16 с persistent volume в ./data/postgres
# ============================================================================

services:
  # ============================================================================
  # PostgreSQL Database
  # ============================================================================
  postgres:
    image: postgres:16-alpine
    container_name: bmft_postgres
    restart: unless-stopped
    
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-bmft}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-bmft}
      PGDATA: /var/lib/postgresql/data/pgdata
    
    volumes:
      # Persistent volume в локальной папке data/postgres
      # Для переноса между нодами копируй всю папку ./data
      - ./data/postgres:/var/lib/postgresql/data
      
      # Миграции можно применить через docker-entrypoint-initdb.d (только при первом запуске)
      # Или через golang-migrate (рекомендуется)
      # - ./migrations:/docker-entrypoint-initdb.d:ro
    
    ports:
      # Порт открыт наружу для локальной отладки (подключение из IDE/go run)
      - "${POSTGRES_PORT:-5432}:5432"
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-bmft}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    
    networks:
      - bmft_network
    
    # Логирование (ограничиваем размер)
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# ============================================================================
# Networks
# ============================================================================
networks:
  bmft_network:
    driver: bridge
    name: bmft_network # Явное имя для подключения извне
