# Dockerfile.telegram_bot

FROM golang:1.24 AS builder

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN go build -o telegram_bot ./cmd/telegram_bot

FROM debian:bookworm

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /src/telegram_bot .

CMD ["./telegram_bot"]