# ============================================================================
# docker-compose.env.yaml — окружение для BMFT бота (БЕЗ самого бота)
# ============================================================================
# Использование:
#   docker-compose -f docker-compose.env.yaml up -d
#   docker-compose -f docker-compose.env.yaml down
#   docker-compose -f docker-compose.env.yaml down -v  # + очистка volumes
# ============================================================================
version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: bmft_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-bmft}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
      - POSTGRES_DB=${POSTGRES_DB:-bmft}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=Europe/Moscow
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-bmft}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - bmft_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  bmft_network:
    driver: bridge
